/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
var CLASS$=Laya.class;
var STATICATTR$=Laya.static;
var View=laya.ui.View;
var Dialog=laya.ui.Dialog;
var Scene=Laya.Scene;
if(!window.ui) window.ui={};
var BattleUI=(function(_super){
		function BattleUI(){
			
			BattleUI.__super.call(this);
		}
		CLASS$(BattleUI,'ui.BattleUI',_super);
		var __proto__=BattleUI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("Battle");
		}
		return BattleUI;
	})(Scene);
var inforUI=(function(_super){
		function inforUI(){
			
			inforUI.__super.call(this);
		}
		CLASS$(inforUI,'ui.inforUI',_super);
		var __proto__=inforUI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("infor");
		}
		return inforUI;
	})(Dialog);
var sayUI=(function(_super){
		function sayUI(){
			
			sayUI.__super.call(this);
		}
		CLASS$(sayUI,'ui.sayUI',_super);
		var __proto__=sayUI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("say");
		}
		return sayUI;
	})(Dialog);
var Sence1UI=(function(_super){
		function Sence1UI(){
			
			Sence1UI.__super.call(this);
		}
		CLASS$(Sence1UI,'ui.Sence1UI',_super);
		var __proto__=Sence1UI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("Sence1");
		}
		return Sence1UI;
	})(Scene);
var Sence1House1UI=(function(_super){
		function Sence1House1UI(){
			
			Sence1House1UI.__super.call(this);
		}
		CLASS$(Sence1House1UI,'ui.Sence1House1UI',_super);
		var __proto__=Sence1House1UI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("Sence1House1");
		}
		return Sence1House1UI;
	})(Scene);
var startUI=(function(_super){
		function startUI(){
			
		    this.bg1=null;
		    this.bg2=null;
		    this.logn=null;
		    this.infor=null;
			startUI.__super.call(this);
		}
		CLASS$(startUI,'ui.startUI',_super);
		var __proto__=startUI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("start");
		}
		return startUI;
	})(Scene);
export {ui as default};