/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
var CLASS$=Laya.class;
var STATICATTR$=Laya.static;
var View=laya.ui.View;
var Dialog=laya.ui.Dialog;
var Scene=Laya.Scene;
if(!window.ui) window.ui={};
var BattleUI=(function(_super){
		function BattleUI(){
			
			BattleUI.__super.call(this);
		}
		CLASS$(BattleUI,'ui.BattleUI',_super);
		var __proto__=BattleUI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("Battle");
		}
		return BattleUI;
	})(Scene);
var inforUI=(function(_super){
		function inforUI(){
			
			inforUI.__super.call(this);
		}
		CLASS$(inforUI,'ui.inforUI',_super);
		var __proto__=inforUI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("infor");
		}
		return inforUI;
	})(Dialog);
var sayUI=(function(_super){
		function sayUI(){
			
			sayUI.__super.call(this);
		}
		CLASS$(sayUI,'ui.sayUI',_super);
		var __proto__=sayUI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("say");
		}
		return sayUI;
	})(Dialog);
var gift1UI=(function(_super){
		function gift1UI(){
			
			gift1UI.__super.call(this);
		}
		CLASS$(gift1UI,'ui.sence.gift1UI',_super);
		var __proto__=gift1UI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("sence/gift1");
		}
		return gift1UI;
	})(Dialog);
var gift3UI=(function(_super){
		function gift3UI(){
			
			gift3UI.__super.call(this);
		}
		CLASS$(gift3UI,'ui.sence.gift3UI',_super);
		var __proto__=gift3UI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("sence/gift3");
		}
		return gift3UI;
	})(Dialog);
var Sence1House2UI=(function(_super){
		function Sence1House2UI(){
			
			Sence1House2UI.__super.call(this);
		}
		CLASS$(Sence1House2UI,'ui.sence.Sence1House2UI',_super);
		var __proto__=Sence1House2UI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("sence/Sence1House2");
		}
		return Sence1House2UI;
	})(Scene);
var Sence1House2_2UI=(function(_super){
		function Sence1House2_2UI(){
			
			Sence1House2_2UI.__super.call(this);
		}
		CLASS$(Sence1House2_2UI,'ui.sence.Sence1House2_2UI',_super);
		var __proto__=Sence1House2_2UI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("sence/Sence1House2_2");
		}
		return Sence1House2_2UI;
	})(Scene);
var Sence2UI=(function(_super){
		function Sence2UI(){
			
			Sence2UI.__super.call(this);
		}
		CLASS$(Sence2UI,'ui.sence.Sence2UI',_super);
		var __proto__=Sence2UI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("sence/Sence2");
		}
		return Sence2UI;
	})(Scene);
var Sence1UI=(function(_super){
		function Sence1UI(){
			
			Sence1UI.__super.call(this);
		}
		CLASS$(Sence1UI,'ui.Sence1UI',_super);
		var __proto__=Sence1UI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("Sence1");
		}
		return Sence1UI;
	})(Scene);
var Sence1House1UI=(function(_super){
		function Sence1House1UI(){
			
			Sence1House1UI.__super.call(this);
		}
		CLASS$(Sence1House1UI,'ui.Sence1House1UI',_super);
		var __proto__=Sence1House1UI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("Sence1House1");
		}
		return Sence1House1UI;
	})(Scene);
var startUI=(function(_super){
		function startUI(){
			
		    this.bg2=null;
		    this.bg1=null;
		    this.logn=null;
		    this.infor=null;
			startUI.__super.call(this);
		}
		CLASS$(startUI,'ui.startUI',_super);
		var __proto__=startUI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("start");
		}
		return startUI;
	})(Scene);
export {ui as default};