/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import playAttack from "./battle/playAttack"
import playDefense from "./battle/playDefense"
import skill1 from "./battle/skill1"
import skill2 from "./battle/skill2"
import skill4 from "./battle/skill4"
import skill5 from "./battle/skill5"
import skill3 from "./battle/skill3"
import skill6 from "./battle/skill6"
import player from "./battle/player"
import per1 from "./battle/per1"
import close from "./player/close"
import playerInfor from "./start/playerInfor"
import loadBattle from "./start/loadBattle"
import closeGift1 from "./gift/closeGift1"
import viedoShow from "./gift/viedoShow"
import closeViedo from "./gift/closeViedo"
import dataGame from "./gift/dataGame"
import closeGift2 from "./gift/closeGift2"
import playmoving from "./start/playmoving"
import outhouse2 from "./doors/sence1/outhouse2"
import inhouse2 from "./doors/sence1/inhouse2"
import outhouse_2 from "./doors/sence1/outhouse_2"
import npc1 from "./sence1/npc1"
import doors from "./sence1/doors"
import npc2 from "./sence1/npc2"
import inHouse2 from "./doors/inHouse2"
import out3 from "./doors/out3"
import out2 from "./doors/out2"
import out from "./doors/out"
import house2 from "./sence1/house2"
import gift1 from "./gift/gift1"
import gift2 from "./gift/gift2"
import viedo from "./gift/viedo"
import gift3 from "./gift/gift3"
import bgMove from "./start/bgMove"
import lognShow from "./start/lognShow"
import loadAssets from "./start/loadAssets"
import gkClick from "./start/gkClick"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("battle/playAttack.js",playAttack);
		reg("battle/playDefense.js",playDefense);
		reg("battle/skill1.js",skill1);
		reg("battle/skill2.js",skill2);
		reg("battle/skill4.js",skill4);
		reg("battle/skill5.js",skill5);
		reg("battle/skill3.js",skill3);
		reg("battle/skill6.js",skill6);
		reg("battle/player.js",player);
		reg("battle/per1.js",per1);
		reg("player/close.js",close);
		reg("start/playerInfor.js",playerInfor);
		reg("start/loadBattle.js",loadBattle);
		reg("gift/closeGift1.js",closeGift1);
		reg("gift/viedoShow.js",viedoShow);
		reg("gift/closeViedo.js",closeViedo);
		reg("gift/dataGame.js",dataGame);
		reg("gift/closeGift2.js",closeGift2);
		reg("start/playmoving.js",playmoving);
		reg("doors/sence1/outhouse2.js",outhouse2);
		reg("doors/sence1/inhouse2.js",inhouse2);
		reg("doors/sence1/outhouse_2.js",outhouse_2);
		reg("sence1/npc1.js",npc1);
		reg("sence1/doors.js",doors);
		reg("sence1/npc2.js",npc2);
		reg("doors/inHouse2.js",inHouse2);
		reg("doors/out3.js",out3);
		reg("doors/out2.js",out2);
		reg("doors/out.js",out);
		reg("sence1/house2.js",house2);
		reg("gift/gift1.js",gift1);
		reg("gift/gift2.js",gift2);
		reg("gift/viedo.js",viedo);
		reg("gift/gift3.js",gift3);
		reg("start/bgMove.js",bgMove);
		reg("start/lognShow.js",lognShow);
		reg("start/loadAssets.js",loadAssets);
		reg("start/gkClick.js",gkClick);
    }
}
GameConfig.width = 640;
GameConfig.height = 1136;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "start.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
