/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import playAttack from "./battle/playAttack"
import playDefense from "./battle/playDefense"
import player from "./battle/player"
import per1 from "./battle/per1"
import close from "./player/close"
import playmoving from "./start/playmoving"
import npc1 from "./sence1/npc1"
import doors from "./sence1/doors"
import npc2 from "./sence1/npc2"
import inHouse2 from "./doors/inHouse2"
import out from "./doors/out"
import bgMove from "./start/bgMove"
import lognShow from "./start/lognShow"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("battle/playAttack.js",playAttack);
		reg("battle/playDefense.js",playDefense);
		reg("battle/player.js",player);
		reg("battle/per1.js",per1);
		reg("player/close.js",close);
		reg("start/playmoving.js",playmoving);
		reg("sence1/npc1.js",npc1);
		reg("sence1/doors.js",doors);
		reg("sence1/npc2.js",npc2);
		reg("doors/inHouse2.js",inHouse2);
		reg("doors/out.js",out);
		reg("start/bgMove.js",bgMove);
		reg("start/lognShow.js",lognShow);
    }
}
GameConfig.width = 640;
GameConfig.height = 1136;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "start.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
